### PR TITLE
Added error catching for barcode

### LINKED ISSUE #473: Harvester indicating success when identifiers are incomplete in the API
The harvester is now "successfully" harvesting samples when identifiers in the API are incomplete or incorrect relative to the manifest or current sample record. 

For example:
image

A record was harvested for ARIK.20190327.CORE.1_DASYHELEA SP. when it should have failed due to a mismatch between the manifest (and physical sample) barcode and the barcode in the API.
image

(API value in the barcode is missing a 0).

image

Luckily, the errorMessage was not erased from the NeonSample table, but we do want instances in which there are mismatches in identifiers to altogether fail.

### PR DESCRIPTION
**Pull request by sunray1**

### CODE REVIEW

**Review by kyule — CHANGES_REQUESTED** [review]
This does work when they both exist and don't match. But it doesn't work in the case of missing barcodes that shouldn't be missing. Is there any issue with making line 341 just "if($sampleArr['sampleCode'] != $viewArr['barcode']){" instead of also including the isset part?

**Comment by sunray1** [comment]
Awesome thanks for checking. If we remove the isset, we're assuming that every sample will have a barcode - that's not correct right?

$sampleArr = manifest + omoccurrences array
$viewArr = what's returned from the API

**Comment by sunray1** [comment]
Are you saying that some samples are missing the barcode in $sampleArr but it is returned in $viewArr? We could just add a condition checking that if so and we can add it.

**Comment by kyule** [comment]
It's true that not all samples have barcodes. But sometimes barcodes are missing in the manifest/occurrence and are present in the API, and sometimes they are missing in the API and are present in the manifest/occurrence. We want an error and a harvesting failure if either of those situations, in addition to if the barcodes are mismatched.

**Comment by sunray1** [comment]
Okay so no adding it, just throw an error?

**Comment by kyule** [comment]
It looks like a ")" was missing. So I put in an additional commit for that. Otherwise, it seems to be working great!.

**Review by kyule — APPROVED** [review]
With the addition of the parentheses, it does work for me.

**Pull request merged**
